#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=repro_attack
#SBATCH --ntasks=1
#SBATCH --time=01:00:00
#SBATCH --mem=32000M
#SBATCH --output=slurm_output_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# Activate your environment
source activate fact2024
# Run your code
srun python -u attack.py --dataset MNIST_USPS --cl_algo SFD
srun python -u attack.py --dataset MNIST_USPS--cl_algo FSC
srun python -u attack.py --dataset MNIST_USPS --cl_algo KFC
srun python -u attack.py --dataset Office-31 --cl_algo SFD
srun python -u attack.py --dataset Office-31--cl_algo FSC
srun python -u attack.py --dataset Office-31 --cl_algo KFC