#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=kfc_office
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=02:00:00
#SBATCH --output=Office-31_KFC_%A.out
#SBATCH --error=Office-31_KFC_%A.err

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate FACT2024 

# Run your code
srun python -u attack.py --dataset Office-31 --cl_algo KFC