#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=FSC_OFFICE-31
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=00:55:00
#SBATCH --output=Office-31_FSC_%A.out
#SBATCH --error=Office-31_FSC_%A.err

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate FACT2024 

# Run your code
srun python -u attack.py --dataset Office-31 --cl_algo FSC