#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=SFD_Office-31
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:50:00
#SBATCH --output=Office-31/EXTRA_METRICS/SFD/%A.out

module purge
module load 2022
module load Anaconda3/2022.05

# activate the environment
source activate FACT2024 

# Run your code
srun python -u attack_extra_metrics.py --dataset Office-31 --cl_algo SFD